name: Haskell CI

on:
  push:
    branches: [ "lurk-milestone-3-refactor" ]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.2.4'
        cabal-version: '3.6.2.0'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
          
    - name: Install Glow lang
      run: curl -L https://glow-lang.org/install/glow-install | sh
      
      
      
    - name: Install Lurk-rs
      uses: actions/checkout@master
      with:
        name: https://github.com/lurk-lang/lurk-rs.git
        submodules: true
        path: ./lurk-rs
    
    - name: Working dirrs
      run: ls
    
      
    - name: Install dependencies
      run: |
        cabal update
        cabal build all --only-dependencies --enable-tests --enable-benchmarks
   #- name: Build
   # run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
